// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type RefreshToken struct {
	ID        string
	ExpiresAt string
	Token     string
	UserID    string
	CreatedAt string
}

type User struct {
	ID             string
	HashedPassword string
	Email          string
}
