// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package database

import (
	"context"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_tokens  (id, expires_at, token, user_id)
VALUES(?,?,?,?)
RETURNING id, expires_at, token, user_id, created_at
`

type CreateTokenParams struct {
	ID        string
	ExpiresAt string
	Token     string
	UserID    string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.ID,
		arg.ExpiresAt,
		arg.Token,
		arg.UserID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTokenByUserID = `-- name: DeleteTokenByUserID :exec
DELETE FROM refresh_tokens 
WHERE user_id = ?
`

func (q *Queries) DeleteTokenByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteTokenByUserID, userID)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, expires_at, token, user_id, created_at FROM refresh_tokens
WHERE token = ? limit 1
`

func (q *Queries) GetToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
